"""add_attachments_to_messages

Revision ID: 5d7851b60f1f
Revises: c40c13daab74
Create Date: 2026-05-26 17:30:58.428848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '5d7851b60f1f'
down_revision: Union[str, None] = 'c40c13daab74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'attachments')
    # ### end Alembic commands ###
