"""add_collab_fields_to_agent_sessions

Revision ID: c40c13daab74
Revises: 
Create Date: 2026-05-25 22:35:39.263635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'c40c13daab74'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_sessions', sa.Column('collab_mode', sa.String(length=20), nullable=True))
    op.add_column('agent_sessions', sa.Column('collab_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_sessions', 'collab_config')
    op.drop_column('agent_sessions', 'collab_mode')
    # ### end Alembic commands ###
